In [4]:
import pandas as pd 
import numpy as np

In [5]:
df= pd.DataFrame({'name':['Karan','Anmol','Aman','Nakul','Rohit','Mohit'],'class':['btech','bca','mba',np.nan,'bca','btech'],'rollno':[12,11,np.nan,10,5,np.nan]})
df

    name  class  rollno
0  Karan  btech    12.0
1  Anmol    bca    11.0
2   Aman    mba     NaN
3  Nakul    NaN    10.0
4  Rohit    bca     5.0
5  Mohit  btech     NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      object
 1   class   5 non-null      object
 2   rollno  4 non-null      float64
dtypes: float64(1), object(2)
memory usage: 276.0+ bytes

In [7]:
df.isnull()

    name  class  rollno
0  False  False   False
1  False  False   False
2  False  False    True
3  False   True   False
4  False  False   False
5  False  False    True

In [8]:
df.isnull().any()

name      False
class      True
rollno     True
dtype: bool

In [9]:
df.isnull().sum()

name      0
class     1
rollno    2
dtype: int64

In [10]:
df.dropna()

    name  class  rollno
0  Karan  btech    12.0
1  Anmol    bca    11.0
4  Rohit    bca     5.0

In [11]:
df

    name  class  rollno
0  Karan  btech    12.0
1  Anmol    bca    11.0
2   Aman    mba     NaN
3  Nakul    NaN    10.0
4  Rohit    bca     5.0
5  Mohit  btech     NaN

In [12]:
df.fillna(10)

    name  class  rollno
0  Karan  btech    12.0
1  Anmol    bca    11.0
2   Aman    mba    10.0
3  Nakul     10    10.0
4  Rohit    bca     5.0
5  Mohit  btech    10.0

In [14]:
s= pd.DataFrame([12,14,18,19,20,22])
s.describe()

               0
count   6.000000
mean   17.500000
std     3.781534
min    12.000000
25%    15.000000
50%    18.500000
75%    19.750000
max    22.000000