In [1]:
import pandas as pd 
import seaborn as sns 

df= sns.load_dataset('titanic')

In [2]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [6]:
df.drop('deck',axis=1, inplace=True)

In [7]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [9]:
df[df.age.isnull()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,Queenstown,no,True
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,Southampton,yes,True
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,Cherbourg,yes,True
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,Cherbourg,no,True
28,1,3,female,NaN,0,0,7.8792,Q,Third,woman,False,Queenstown,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,0,3,male,NaN,0,0,7.2292,C,Third,man,True,Cherbourg,no,True
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,Southampton,no,False
868,0,3,male,NaN,0,0,9.5000,S,Third,man,True,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,Southampton,no,False

In [10]:
df.who.value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [11]:
df_man= df[df.loc[:,'who']=='man']

In [12]:
df_man

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,Southampton,no,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

In [20]:
man_age_mean=df_man.age.mean()
man_age_mean

33.17312348668281

In [19]:
df_man[df_man.age.isnull()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,Queenstown,no,True
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,Southampton,yes,True
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,Cherbourg,no,True
29,0,3,male,NaN,0,0,7.8958,S,Third,man,True,Southampton,no,True
36,1,3,male,NaN,0,0,7.2292,C,Third,man,True,Cherbourg,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
839,1,1,male,NaN,0,0,29.7000,C,First,man,True,Cherbourg,yes,True
846,0,3,male,NaN,8,2,69.5500,S,Third,man,True,Southampton,no,False
859,0,3,male,NaN,0,0,7.2292,C,Third,man,True,Cherbourg,no,True
868,0,3,male,NaN,0,0,9.5000,S,Third,man,True,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,Southampton,no,True

In [21]:
df_man_index= df_man[df_man.age.isnull()].index
df_man_index

Index([  5,  17,  26,  29,  36,  42,  45,  46,  48,  55,
       ...
       825, 826, 828, 832, 837, 839, 846, 859, 868, 878],
      dtype='int64', length=124)

In [22]:
df.loc[df_man_index,'age']=man_age_mean

In [24]:
df.isnull().sum()

survived        0
pclass          0
sex             0
age            53
sibsp           0
parch           0
fare            0
embarked        2
class           0
who             0
adult_male      0
embark_town     2
alive           0
alone           0
dtype: int64

In [25]:
df.loc[df_man_index,:]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
5,0,3,male,33.173123,0,0,8.4583,Q,Third,man,True,Queenstown,no,True
17,1,2,male,33.173123,0,0,13.0000,S,Second,man,True,Southampton,yes,True
26,0,3,male,33.173123,0,0,7.2250,C,Third,man,True,Cherbourg,no,True
29,0,3,male,33.173123,0,0,7.8958,S,Third,man,True,Southampton,no,True
36,1,3,male,33.173123,0,0,7.2292,C,Third,man,True,Cherbourg,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
839,1,1,male,33.173123,0,0,29.7000,C,First,man,True,Cherbourg,yes,True
846,0,3,male,33.173123,8,2,69.5500,S,Third,man,True,Southampton,no,False
859,0,3,male,33.173123,0,0,7.2292,C,Third,man,True,Cherbourg,no,True
868,0,3,male,33.173123,0,0,9.5000,S,Third,man,True,Southampton,no,True
878,0,3,male,33.173123,0,0,7.8958,S,Third,man,True,Southampton,no,True

In [26]:
# Titanic-Dataset

In [27]:
df= pd.read_csv('Titanic-Dataset.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [28]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [33]:
df.Name.str.split(',').str[1].str.split('.').str[0]

0         Mr
1        Mrs
2       Miss
3        Mrs
4         Mr
       ...
886      Rev
887     Miss
888     Miss
889       Mr
890       Mr
Name: Name, Length: 891, dtype: object

In [34]:
df.loc[:,'new']=df.Name.str.split(',').str[1].str.split('.').str[0]

In [35]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Rev
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Miss
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Miss
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Mr
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Mr

In [36]:
df.new.value_counts()

new
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Mlle              2
Major             2
Col               2
the Countess      1
Capt              1
Ms                1
Sir               1
Lady              1
Mme               1
Don               1
Jonkheer          1
Name: count, dtype: int64